---
title: "Processing NM Outputs"
author: "McG8"
date: "3/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r packages}
library(tidyverse)
```

```{r loading data}
wd <- getwd()
dir <- choose.dir(default = "/output", caption = "Choose folder containing NM outputs")
setwd(dir)
allfiles <- list.files(dir)
dataindex <- grep(".csv", allfiles)
file_orig <- allfiles[dataindex]

rawdata <- do.call("bind_rows", lapply(file_orig, function(x) {
  dat <- read_csv(x)
  dat$file_orig <- tools::file_path_sans_ext(x)
  dat
}))
setwd(wd)
```

```{r tidying data}
cleanert <- rawdata %>%
  filter(grepl("_thresh", file_orig) == TRUE) %>%
  mutate(img_nmbr = as.numeric(factor(file_orig))) %>%
  mutate(cell_nmbr = X1) %>%
  select(Area, Feret, FeretX, FeretY, Mean, img_nmbr, cell_nmbr, file_orig)
names(cleanert) <- tolower(names(cleanert))
cleanert <- as.data.frame(cleanert)
tidy <- cleanert %>%
  mutate(percent_pos = 1 - (mean/255)) %>%
  mutate(pos_area = percent_pos * area)
```